### ISSUE TITLE
VisualStudio 2017 can not build it

### ISSUE THREAD

**Issue by DeveloperKen** [Eryux/miband-heartrate#2]
My visualstudio 2017 can not build it.
The reference "Windows" is marked as unavailable, and namespace "Windows.Devices" is missing.
Microsoft Docs shows it is a namespace for UWP applications, not for winforms.
How can I get the project work? Should I switch the project to UWP? (But will winform work still?)

Thanks for helping.

**Comment by DeveloperKen** [comment]
for more information, i ran the visualstudio installer and fixed the software. but it done nothing.

**Comment by Eryux** [comment]
Do you have Windows SDK installed ? 
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

**Comment by DeveloperKen** [comment]
> Do you have Windows SDK installed ?
> https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

Thanks for that. I am installing it. I thought the SDK is included in the VisualStudio Installer in the past...

**Comment by DeveloperKen** [comment]
The include "Windows" is located at
` C:\Program ` Files (x86)\Windows Kits\10\UnionMetadata\[YOUR_VERSION_HERE]\Windows.winmd
I have fixed the problem. Just for who have the same problem.
