### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by anshmishra** [Eryux/miband-heartrate#3]
the window shows "Connected | Not Auth"

**Comment by RuckSkin** [comment]
Same issuse on my PC.

**Comment by Eryux** [comment]
Checked today, worked well for me. Have you followed all these steps ?

-    Un-pairing your Mi Band 2 from any devices
-    Pairing Mi Band 2 to your computer
-    Launch MiBand-Heartrate.exe
-    Select your device Mi Band 2 from the list and then connect (if no device showed, be sure to un-paired and paired your device correctly, turned on the bluetooth adapter and the wifi).
-    **Click on lock for authenticate your device and push Mi Band 2 button**
-    Start monitoring heartrate by clicking on start button

If even by following these steps it's not working, can you post your Mi Band firmware version and your Windows version

**Comment by RuckSkin** [comment]
Yeah but now the Mit Band cant Turn in again. Think there was Problem with the Band.Is there maybe a Was to do this with Others Band's Like the Band 4 ?Am 02.03.2021 00:33 schrieb "C. Nicolas" <notifications@github.com>:
Checked today, worked well for me. Have you followed all these steps ?
Un-pairing your Mi Band 2 from any devicesPairing Mi Band 2 to your computerLaunch MiBand-Heartrate.exeSelect your device Mi Band 2 from the list and then connect (if no device showed, be sure to un-paired and paired your device correctly, turned on the bluetooth adapter and the wifi).Click on lock for authenticate your device and push Mi Band 2 buttonStart monitoring heartrate by clicking on start button
If even by following these steps it's not working, can you post your Mi Band firmware version and your Windows version

**Comment by Eryux** [comment]
Due to the newer version 2.0.0 of the application, does the problem persist ?

The application should now work for Mi Band 2 and 4.

**Comment by Eryux** [comment]
Lack of details on the error and no news.
