### ISSUE TITLE
Auto-Auth for Mi Band 2

### ISSUE THREAD

**Issue by YorVeX** [Eryux/miband-heartrate#6]
I don't know about other Mi Band versions, but for my Mi Band 2 there is no reason why someone would want to connect but then not auth. Maybe on other models it makes sense to have an extra step (documentation says something about a device list being shown first on Mi Band 4 after connection) but for Mi Band 2 it would be great if the Auth step could just happen automatically after a successful connection to skip this step.

**Comment by Eryux** [comment]
There's no extra step for Mi Band 2 if you use the last version of the app, or I don't see the problem ? Just connect to the device and it will launch the auth process automatically. In fact connection and pairing is done when you connect to the device through Windows control panel, the software only manage auth and communication.

**Comment by YorVeX** [comment]
Ugh, how do I know whether I have the latest version though? File version just says 1.0.0.0 and I can't find an About box somewhere. I will redownload and try again.

**Comment by YorVeX** [comment]
Oh nvm, there has been an update just a few days ago, I totally missed that. The changelog on the "releases" page doesn't really indicate any changes to the authing mechanism though.

**Comment by Eryux** [comment]
Fixed on version 2.0.0
