### ISSUE TITLE
Occasional errors while trying to access heartrate.txt file in continuous mode

### ISSUE THREAD

**Issue by YorVeX** [Eryux/miband-heartrate#8]
During a longer session (several hours) this happend twice for me:

![image](https://user-images.githubusercontent.com/528974/113539133-51588980-95dd-11eb-88e1-9e6bd8402aeb.png)

The German part of the error message says that the process can't access the file because it is used by another process.

I am pretty sure that this is because I have OBS reading this file regularly. But as far as I know OBS reads it with a file access mode that allows shared access. The problem is that the current code just uses a StreamWriter without any parameters. Something like this should fix this:

```
var file = File.Open(file, FileMode.OpenOrCreate, FileAccess.Write, FileShare.Read);
using (StreamWriter f = new StreamWriter(file))
...
```

**Comment by Eryux** [comment]
Fixed on 2.1.0
